### ISSUE TITLE
Custom UserAgent 

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#10]
Have the option to 
- manually set a useragent string
- select a useragent string from a dropdown (pre-defined useragents basded on a list of current browsers)

**Comment by dwsmart** [comment]
Be neat if viewport could be specified too, perhaps to match the predefined where appropriate.

**Comment by dwsmart** [comment]
Sensible solution!

**Comment by workeffortwaste** [comment]
Added in 0.2.0
