### ISSUE TITLE
Some snippets return only for first URL

### ISSUE THREAD

**Issue by dwsmart** [workeffortwaste/horseman#105]
There's some snippets that still seem to only return for the first result,

`Carbon Footprint`, `Image Size Decompressed`, Image Size Transferred` are an example
![carbon-fp](https://user-images.githubusercontent.com/11179452/196684437-fe9d911d-ab6a-4280-aa9f-194d3907aaf5.png)

Crawl JSON export attached:
[https_tamethebots.comblog-n-bits-2022-10-19T12_00_31.891Z.json.zip](https://github.com/workeffortwaste/horseman/files/9820197/https_tamethebots.comblog-n-bits-2022-10-19T12_00_31.891Z.json.zip)

**Comment by workeffortwaste** [comment]
This was a weird service worker issue. I've not blocked workers in Horseman in line with how other crawlers work.
