### ISSUE TITLE
Increase scroll bar size

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#11]
I find it hard to hit the scrollbars :) 
(Maybe have a general "settings" screen to set some properties such as scrollbar width, font size, dark mode?)

**Comment by workeffortwaste** [comment]
The plan is to have it increase the size of the scrollbars when you get close to them.

**Comment by workeffortwaste** [comment]
Increased in [v0.1.4](https://github.com/workeffortwaste/horseman/milestone/5)
