### ISSUE TITLE
Sorting on resource size decompressed and resource size transferred snippets

### ISSUE THREAD

**Issue by dwsmart** [workeffortwaste/horseman#113]
Super pedantic one I spotted

If you open the explore and sort by size, it's alpha-numeric:

![image](https://user-images.githubusercontent.com/11179452/213500917-be9a4f9d-f991-4452-a4ff-72ddd28d2c77.png)

Presumably the size is a string, or cast to a string somewhere, other snippets I've created where the value is a `int` or `float` seem to order correctly.

Super pedantic anyways,

**Comment by workeffortwaste** [comment]
Fixed.
