### ISSUE TITLE
Have a snippet "marketplace" for people to share their snippets

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#12]
I would find it very useful to be able to share my snippets with others and to see what others come up with. An internal "snippet marketplace" with a "Click to install snippet" functionality would be cool.

**Comment by workeffortwaste** [comment]
I'll have a think about how a share flow directly inside the app could work.

**Comment by workeffortwaste** [comment]
I'm going to put this on the backburner for a while as the tool isn't popular enough yet to invest as much time as this feature would need.
