### ISSUE TITLE
gethorseman.app is down

### ISSUE THREAD

**Issue by admariner** [workeffortwaste/horseman#126]
# Horseman Down!
## Or is they?
_(2 entities, so it makes sense use they)_

gethorseman.app went numb a few days ago

[Or is it](https://answers.netlify.com/t/new-feature-browse-files-in-your-deploy-with-the-deploy-file-browser/105196)

![download](https://github.com/workeffortwaste/horseman/assets/8210250/9c9f8e29-a955-4264-b9b1-1c58ecf7123d)

**Comment by workeffortwaste** [comment]
Oh no!

Hang on.

**Comment by workeffortwaste** [comment]
I've reached out to Netlify as all my sites are down and my account has
been suspended!
