### ISSUE TITLE
Automatically name CSV export to include domain, date and time

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#13]
automaticall name the downloadable CSV export file to something like `domain_date_time_export.csv`, so old exports won't get overwritten or I have to come up with a new name for every file.

**Comment by workeffortwaste** [comment]
I'll get that sorted for the next minor release.

**Comment by workeffortwaste** [comment]
Added in [v0.1.2](https://github.com/workeffortwaste/horseman/milestone/2)

It takes the format of `https_defaced.dev-2022-03-24T14_19_12.464Z.csv`
