### ISSUE TITLE
Respect robots.txt

### ISSUE THREAD

**Issue by workeffortwaste** [workeffortwaste/horseman#16]
Currently the robots.txt file is not parsed and URLs are queued freely.

Include a robots.txt parser in Horseman.

* Allow for URLS to be queued based on their robots.txt status
* Pass the robots.txt status for each URL to the snippet scope so it can be used as crawl data

**Comment by workeffortwaste** [comment]
This looks like it would slot it easily.

https://github.com/samclarke/robots-parser

**Comment by chrishaensel** [comment]
But please make it an optional feature :D

**Comment by workeffortwaste** [comment]
Done in 0.2.0
