### ISSUE TITLE
Some Custom Web Component Attributes trigger Depreciated Elements

### ISSUE THREAD

**Issue by dwsmart** [workeffortwaste/horseman#20]
[on this page](https://testing.tamethebots.com/web-component.html) 
`<ttb-test-component text="This is passed through attributes."></ttb-test-component>`

Triggers the depreciated elements test, presumably due to the `text` attribute?

**Comment by workeffortwaste** [comment]
The deprecated element/attribute snippets were taken from elsewhere. I'm not entirely convinced with their robustness.

I'll probably strip them out of the next release and write my own at some point.

**Comment by workeffortwaste** [comment]
Deprecated elements check is working as expected, it's the attributes check that's causing a lot of problems so I've removed it from [v0.1.3](https://github.com/workeffortwaste/horseman/milestone/4)
