### ISSUE TITLE
Console Log entries display as [object Object]

### ISSUE THREAD

**Issue by dwsmart** [workeffortwaste/horseman#22]
[on this url](https://testing.tamethebots.com/websocket.html) 

It detects log entries, but the display is [object Object], so seems like something needs a dose of `JSON.stringify()`, or other serialization

![horseman-screenshot](https://user-images.githubusercontent.com/11179452/159999474-482bc6ef-ef0e-4430-a305-9f0a43b3704f.png)

**Comment by workeffortwaste** [comment]
Fixed in [v0.1.3](https://github.com/workeffortwaste/horseman/milestone/4)
