### ISSUE TITLE
Input URLs from list

### ISSUE THREAD

**Issue by dwsmart** [workeffortwaste/horseman#23]
I find it really helpful to specify a list of URLs to crawl sometimes, perhaps a text upload, simple pages or parse from a sitemap

**Comment by workeffortwaste** [comment]
This should be fairly trivial with https://github.com/sindresorhus/get-urls

I'll be able to replicate Screaming Frog in that you can paste in any chunk of text and it will extract URLs.

**Comment by workeffortwaste** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/49479599/160675859-606ba832-c907-4847-b513-0601501661fd.png">

It'll now discover URLS from any text file, doesn't matter if it's a CSV, Excel file, a random bunch of URLS you've throw into Notepad.

You can drag & drop, open the file, paste the file from explorer, or even paste file contents!

**Comment by dwsmart** [comment]
Looks awesome!

**Comment by workeffortwaste** [comment]
Added in [v0.1.3](https://github.com/workeffortwaste/horseman/milestone/4)
