### ISSUE TITLE
Ask before closing app when crawl is running

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#26]
When hitting the "X" or ALT+F4 to close the app during an active / paused crawl, I would likle to see a dialog popup asking if I really want to to that (and agree to be losing the data)

**Comment by workeffortwaste** [comment]
Good catch, this should be fairly easy to implement.

**Comment by workeffortwaste** [comment]
Added in [v0.1.3](https://github.com/workeffortwaste/horseman/milestone/4)
