### ISSUE TITLE
Tooltip is misplaced and won't disappear

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#45]
When hovering over the "Pause" buttoin, the tooltip appeared at the top left of the app and won't disapprear, even after changing views, resizing, clicking buttons and hovering over the other "action" buttons which have tooltips. The tooltips of the other buttons appear at the correct location and disappear on `mouseleave`.
![image](https://user-images.githubusercontent.com/5918075/161210976-bd15f043-c069-4829-be8b-389ced0cfc11.png)

**Comment by workeffortwaste** [comment]
https://floating-vue.starpad.dev/api/#global
