### ISSUE TITLE
Allow all homepage options from the crawl page

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#46]
When clearing a crawl, I might want to get back to the "main" starting view to do the next xrawl with a text list of URLs. Currently, all I can do is enter a starting URL to start a fresh crawl, because there is no way (or am I missing it?) to get back to the main screen.

**Comment by workeffortwaste** [comment]
I've not yet decided on how to implement the text list crawl, and other crawl options.

I'm thinking of having the start crawl button everywhere be something like this, with the different crawls available in the drop down.

![xUrjI.png](https://user-images.githubusercontent.com/49479599/161296891-8dea1c31-0f0b-4fce-aae7-a0910620b71e.png)

**Comment by workeffortwaste** [comment]
Added in 0.2.0
