### ISSUE TITLE
Show "Explore" button on extended table when extended data is available

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#47]
Just like with the core data tables, show "Explore" button when extended data is available.

**Comment by workeffortwaste** [comment]
Can you clarify what you mean by this issue?

**Comment by chrishaensel** [comment]
Hey Chris

sorry for replying so slow... busy days.
![image](https://user-images.githubusercontent.com/5918075/174724998-339115bb-598c-494b-a8b9-224a5e152524.png)

I meant to ask to have a button displayed like you do with the built-in "extended data tables" like the response heaser table - just also show this for extended data tables like for example my headings data. 
![image](https://user-images.githubusercontent.com/5918075/174725304-41909237-3422-41b0-b74d-9d2386529e92.png)

**Comment by workeffortwaste** [comment]
Added via comment directives.
