### ISSUE TITLE
Spider from List URLS

### ISSUE THREAD

**Issue by jessthebp** [workeffortwaste/horseman#50]
"Crawl from list" currently does not support additional spidering. This feature would allow the user to choose whether to just crawl a list or spider out from a list with multiple starting URLs.

**Comment by workeffortwaste** [comment]
Feature added in 0.2.0 via a toggle on the List Crawl page.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/49479599/177740605-da69cf6f-941a-4edd-9826-9f5a0f8d2ea7.png">
