### ISSUE TITLE
Implement snippets table view

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#53]
I would like to have the ability to switch from card to table view in the snippets view. It would be easier to find the snippet I want to have if the list was in the form of a table.

**Comment by workeffortwaste** [comment]
This has now been added via comment directives.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/49479599/177313469-54f5d95f-eb6a-4e04-ba32-8ab701034aab.png">
