### ISSUE TITLE
Allow to set custom cookies

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#57]
I would love to see an option to set custom cookies for the puppeteer instances.
A sample use case could be to bypass Cloudflare caching.

`await page.setCookie({
        const urlObject = new URL(page_url);
        const hostName = urlObject.hostname;
        'url': 'https://' + hostName,
        'name': 'wordpress',
        'value': 'seo-dept'
});`

**Comment by workeffortwaste** [comment]
Added in 0.2.0
