### ISSUE TITLE
Missing status code tags

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#74]
When HTTP status codes are displayed, show text info for the meaning of the status code on hover. 
![image](https://user-images.githubusercontent.com/5918075/181230744-12c8c59c-1f29-4721-b1d5-6c65cc8e3ab5.png)

**Comment by workeffortwaste** [comment]
How have you managed to get one without a status? 🤔

**Comment by chrishaensel** [comment]
Haha, that is a very good question. I don't know which site I crawled. Will try to find out and let you know.

**Comment by workeffortwaste** [comment]
Fixed all the missing status code tags in 0.2.0 using statuscodes.org for a reference.

With regards to the tooltips that's not something I'll add, but I'll expose the full redirect chain to the snippets. At that point it will be easy to make a snippet that outputs information about what the code means via a snippet.
