### ISSUE TITLE
Fix color coding for lowercase "fail", "warn", "pass" return values

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#78]
Currently, color codig the pills only works with uppercase first letter of "fail", "pass" and "warn" return values. 
Please make it accept also lowercase coz me == lazy :) 
![image](https://user-images.githubusercontent.com/5918075/182707946-ee89d1dd-861f-4056-98c4-0e7f7641739a.png)

**Comment by workeffortwaste** [comment]
Fixed in 0.2.0
