### ISSUE TITLE
Crawler removes www from URLs

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#91]
I have a set of URLs starting with https://www..... 
Horseman is removing the "www" from the URL, only to be then redirected by the server to the "www" version - and then reporting a 301 redirect where there would be none if the "www" had been left in place.

**Comment by workeffortwaste** [comment]
That seems odd. Want to slack me some examples so I can check it out?

**Comment by chrishaensel** [comment]
Sent some URLs via slack. Forgot to mention that this happened during a "list crawl".

**Comment by workeffortwaste** [comment]
Found the cause. 👍

![Screenshot_20220904-213608.png](https://user-images.githubusercontent.com/49479599/188332465-3da23c48-4ff3-4234-85e2-f0c66d1c3005.png)

**Comment by workeffortwaste** [comment]
Fixed.
