### ISSUE TITLE
Resizing leads to design issues

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#94]
Resizing the app window leads to overlapping design elements (snippet pills wrapping and being positioned underneath other elements)
https://user-images.githubusercontent.com/5918075/191174840-bf222d67-7ae3-4d23-8843-468443c7b2bc.mp4

**Comment by workeffortwaste** [comment]
![horseman-screenshot](https://user-images.githubusercontent.com/49479599/191849346-ca326b86-7098-48d1-89eb-0d621266dda7.png)

I can't replicate this one :(

**Comment by workeffortwaste** [comment]
Fixed.
