### ISSUE TITLE
Console.* extended tables show all log outputs combined

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#95]
All the console.* (log|warn|error) tables display all console output. there is no distinction between the different console outputs, as one would expect to have console.log, .warn and .error.
![image](https://user-images.githubusercontent.com/5918075/191175177-e8689846-7c3f-4583-9b82-cdf269544e4c.png)

**Comment by workeffortwaste** [comment]
Fixed in 0.2.1
