### ISSUE TITLE
User-Agent string passed within JSON on startup seemingly not used when crawling

### ISSUE THREAD

**Issue by chrishaensel** [workeffortwaste/horseman#97]
When using a headers.json on startup to pass my custom headers for crawling, Horseman apparently does not take the user-agent string I am passing. 

my headers.json file:
`{
    "User-Agent": "MY-CUSTOM-UA"
}`

Starting Horseman with 
`horseman.exe --headers="C:\Users\holyshit\Desktop\headers.json"`

**Comment by workeffortwaste** [comment]
Using a custom headers file will now disable device emulation.
